Upgrade OpenAPI spec to v3
openfisca/country-template pull request #128
Opened 2022-11-03 23:25 UTC by maukoquiroga

#### New Features

- Upgrade OpenAPI specification of the API to v3 from Swagger v2.
- Continuously validate OpenAPI specification.

#### Breaking changes

- Drop support for OpenAPI specification v2 and prior.
- Users relying on the aforesaid can use [https://converter.swagger.io/api/convert?url=OAS2_YAML_OR_JSON_URL] to migrate ([example](https://web.archive.org/web/20221103230822/https://converter.swagger.io/api/convert?url=https://api.demo.openfisca.org/latest/spec)).

2022-11-11 09:32 UTC, MattiSG requested changes
Beyond the requested changes here (blocking but trivial, basically just CHANGELOG copy), this is blocked until https://github.com/openfisca/legislation-explorer/ is updated to support OpenAPI v3, as https://demo.openfisca.org will automatically deploy the latest version of this package.

2022-11-11 09:32 UTC, MattiSG commented on CHANGELOG.md
> +- Upgrade OpenAPI specification of the API to v3 from Swagger v2.
- Upgrade Web API specification to OpenAPI v3.

2022-11-11 09:32 UTC, MattiSG commented on CHANGELOG.md
> +#### New Features
```suggestion
#### New features
```

2022-11-11 09:32 UTC, MattiSG commented on CHANGELOG.md
> +- Continuously validate OpenAPI specification.
Inaccurate in this package.
```suggestion
```

2022-11-11 09:32 UTC, MattiSG commented on CHANGELOG.md
> +- Users relying on the aforesaid can use [this](https://converter.swagger.io/api/convert?url=OAS2_YAML_OR_JSON_URL) to migrate ([example](https://web.archive.org/web/20221103230822/https://converter.
```suggestion
  - Users relying on OpenAPI v2 can use [Swagger Converter](https://converter.swagger.io/api/convert?url=OAS2_YAML_OR_JSON_URL) to migrate ([example](https://web.archive.org/web/20221103230822/https://converter.swagger.io/api/convert?url=https://api.demo.openfisca.org/latest/spec)).
```

2022-11-11 09:32 UTC, MattiSG commented on setup.py
> +    version = "4.0.0.rc1",
Update before merge.

2022-11-11 09:32 UTC, MattiSG commented on setup.py
> +        "OpenFisca-Core[web-api] >= 36.0.0.rc1, < 37.0.0",
Update before merge.

2022-12-08 12:47 UTC, maukoquiroga commented
> Beyond the requested changes here (blocking but trivial, basically just CHANGELOG copy), this is blocked until https://github.com/openfisca/legislation-explorer/ is updated to support OpenAPI v3, as https://demo.openfisca.org will automatically deploy the latest version of this package.

Legislation explorer already handles OpenAPI v3.

2022-12-12 07:42 UTC, MattiSG approved these changes

2022-12-12 07:45 UTC, merged